HTTP/1.1 428 Precondition Required
server: nginx
date: Fri, 03 Mar 2017 10:00:36 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2396
x-ratelimit-reset: 1488538622
cache-control: no-cache
x-request-id: 8e6cfeba-61f3-4449-9d95-dceaa1be30b0
x-runtime: 0.033649
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: DENY
x-permitted-cross-domain-policies: none
x-xss-protection: 1; mode=block

{"message":"DNSSEC cannot be disabled because it is not enabled"}
