HTTP/1.1 200 OK
Server: nginx/1.5.8
Date: Tue, 14 Jan 2014 18:40:28 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Status: 200 OK
X-Dnsimple-API-Version: 1.0.0
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization,Accepts,Content-Type,X-Dnsimple-Token,X-Dnsimple-Domain-Token,X-CSRF-Token,x-requested-with
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
X-UA-Compatible: IE=Edge,chrome=1
ETag: "2b76f0ea88c7e95384506ac576d23d01"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: aaf5915a32924165d4f45779689831fa
X-Runtime: 0.042263
Strict-Transport-Security: max-age=315360000

{"certificate":{"id":4576,"domain_id":79569,"contact_id":11549,"name":"www","state":"submitted","csr":"-----BEGIN NEW CERTIFICATE REQUEST-----\nRHr2akB4KMba6FMAsvlStnO/2ika16hNx+d3smPNsER+HA==\n-----END NEW CERTIFICATE REQUEST-----\n","ssl_certificate":null,"private_key":"-----BEGIN RSA PRIVATE KEY-----\nUeXbFi7o+nuPfRhpBFQEKwacKFc3Hnc1hH6UsnC0KY25cUif7yz38A==\n-----END RSA PRIVATE KEY-----\n","approver_email":"example@example.net","expires_on":"2014-09-17","created_at":"2013-09-17T21:54:42Z","updated_at":"2013-09-17T22:25:36Z","configured_at":"2013-09-17T22:25:01Z"}}