HTTP/1.1 204 No Content
server: nginx
date: Thu, 24 Mar 2016 11:05:38 GMT
connection: keep-alive
status: 204 No Content
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2397
x-ratelimit-reset: 1458821049
cache-control: no-cache
x-request-id: 967713d5-a203-40ee-875c-1df07868b7eb
x-runtime: 0.147576
strict-transport-security: max-age=31536000

