HTTP/1.1 204 No Content
server: nginx
date: Tue, 03 May 2016 08:00:35 GMT
connection: keep-alive
status: 204 No Content
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2397
x-ratelimit-reset: 1462265481
cache-control: no-cache
x-request-id: f0a48944-1c61-41f4-b379-04f8644d883b
x-runtime: 0.122787
strict-transport-security: max-age=31536000

