HTTP/1.1 400 Bad Request
server: nginx
date: Sun, 21 Feb 2016 13:11:11 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
status: 400 Bad Request
x-ratelimit-limit: 4000
x-ratelimit-remaining: 3997
x-ratelimit-reset: 1456063540
cache-control: no-cache
x-request-id: d7a0eb63-77eb-4488-bc55-c129ed8fe192
x-runtime: 11.912567

{"message":"Validation failed","errors":{"base":["You must provide an authorization code for the domain"]}}