HTTP/1.1 400 Bad Request
server: nginx
date: Tue, 23 Sep 2025 10:21:06 GMT
content-type: application/json; charset=utf-8
content-length: 137
connection: keep-alive
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2397
x-ratelimit-reset: 1758626142
x-work-with-us: Love automation? So do we! https://dnsimple.com/jobs
cache-control: no-cache
x-request-id: 22761da9-ad02-4970-add5-e26602b09bb5
x-runtime: 0.115194
strict-transport-security: max-age=63072000

{"message":"Validation failed","errors":{"creates":[{"index":0,"message":"Validation failed","errors":{"record_type":["unsupported"]}}]}}
