HTTP/1.1 200 OK
server: nginx
date: Tue, 19 Jan 2016 20:57:38 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
status: 200 OK
x-ratelimit-limit: 4000
x-ratelimit-remaining: 3996
x-ratelimit-reset: 1453239045
etag: W/"165299b0ea3e5c1c80f1ae622146626f"
cache-control: max-age=0, private, must-revalidate
x-request-id: 4c0679ed-5c79-41bf-84cb-0dc2250a07ce
x-runtime: 0.127802
strict-transport-security: max-age=31536000

{"data":{"id":1,"account_id":1010,"label":"Default","first_name":"First","last_name":"User","job_title":"CEO","organization_name":"Awesome Company","email":"first@example.com","phone":"+18001234567","fax":"+18011234567","address1":"Italian Street, 10","address2":"","city":"Roma","state_province":"RM","postal_code":"00100","country":"IT","created_at":"2016-01-19T20:50:26Z","updated_at":"2016-01-19T20:50:26Z"}}
