HTTP/1.1 200 OK
Server: nginx/1.4.4
Date: Tue, 14 Jan 2014 17:45:57 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Status: 200 OK
X-DNSimple-API-Version: 1.0.0
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization,Accepts,Content-Type,X-DNSimple-Token,X-DNSimple-Domain-Token,X-CSRF-Token,x-requested-with
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
X-UA-Compatible: IE=Edge,chrome=1
ETag: "eaafff1bd6f4251411afaf624b31ba67"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: fea9cce456c8be69c4b0dec81452726b
X-Runtime: 0.034644
Strict-Transport-Security: max-age=315360000

{"user":{"id":2,"email":"example@example.com","referral_token":"04b12390f6204e","single_access_token":"fCF0n6OTW5n4NtFh8W","default_contact_id":null,"phone":null,"country_code":null,"authy_identifier":null,"authy_verified_at":null,"domain_count":2,"domain_limit":50,"login_count":2,"failed_login_count":0,"unsubscribed_at":null,"created_at":"2013-11-08T17:20:58Z","updated_at":"2014-01-14T17:45:57Z","first_name":null,"last_name":null}}