HTTP/1.1 200 OK
Server: nginx
Date: Mon, 15 Dec 2014 17:39:53 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Status: 200 OK
Strict-Transport-Security: max-age=631138519
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization,Accepts,Content-Type,X-DNSimple-Token,X-DNSimple-Domain-Token,X-CSRF-Token,x-requested-with
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
ETag: "8b6a002b2d4d8eecfd1c9a3bdd70bec1"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 15b1f2e3-d6f7-418b-bc66-7af13fca1cde
X-Runtime: 0.096886
Strict-Transport-Security: max-age=315360000

{"dns_template_record":{"id":8868,"dns_template_id":2947,"name":"ww1","content":"127.0.0.1","ttl":3600,"prio":null,"record_type":"ALIAS","created_at":"2014-12-15T17:25:20.431Z","updated_at":"2014-12-15T17:25:20.431Z"}}
