HTTP/1.1 200 OK
Server: nginx/1.4.4
Date: Tue, 14 Jan 2014 18:27:45 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Status: 200 OK
X-Dnsimple-API-Version: 1.0.0
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization,Accepts,Content-Type,X-Dnsimple-Token,X-Dnsimple-Domain-Token,X-CSRF-Token,x-requested-with
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
X-UA-Compatible: IE=Edge,chrome=1
ETag: "67a9bfb8046724e79c7244d3c2458e65"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: bb7cbc5a32833ea4d59c185b0ab67915
X-Runtime: 0.205329
Strict-Transport-Security: max-age=315360000

{"record":{"id":1495,"domain_id":6,"parent_id":null,"name":"www","content":"1.2.3.4","ttl":3600,"prio":null,"record_type":"A","system_record":null,"created_at":"2014-01-14T18:25:56Z","updated_at":"2014-01-14T18:26:04Z"}}