HTTP/1.1 204 No Content
Server: nginx
Date: Mon, 22 Dec 2014 15:45:43 GMT
Connection: close
Status: 204 No Content
Strict-Transport-Security: max-age=631138519
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization,Accepts,Content-Type,X-DNSimple-Token,X-DNSimple-Domain-Token,X-CSRF-Token,x-requested-with
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
Cache-Control: no-cache
X-Request-Id: 4d6a3dec-6e12-4335-aaf6-378bafa4eb73
X-Runtime: 0.037958
Strict-Transport-Security: max-age=315360000

