HTTP/1.1 200 OK
server: nginx
date: Tue, 03 May 2016 08:04:20 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
status: 200 OK
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2394
x-ratelimit-reset: 1462265481
etag: W/"743142eab9fecf3edb41e9b3f30a903f"
cache-control: max-age=0, private, must-revalidate
x-request-id: 6484e900-7255-4194-9ff8-ae5650ebd765
x-runtime: 0.138017
strict-transport-security: max-age=31536000

{"data":{"id":301,"template_id":268,"name":"","content":"mx.example.com","ttl":600,"priority":10,"type":"MX","created_at":"2016-05-03T08:03:26Z","updated_at":"2016-05-03T08:03:26Z"}}
