HTTP/1.1 204 No Content
server: nginx
date: Mon, 15 Feb 2016 17:05:39 GMT
connection: keep-alive
status: 204 No Content
x-ratelimit-limit: 4000
x-ratelimit-remaining: 3993
x-ratelimit-reset: 1455559348
cache-control: no-cache
x-request-id: d681e116-4a27-45a6-b571-3f74bfafb1f4
x-runtime: 0.520613
strict-transport-security: max-age=31536000

