---
inherit_from:
  - .rubocop_todo.yml
  - .rubocop_dnsimple.yml

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - 'vendor/**/*'
