# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dnsimple-ruby}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Anthony Eden"]
  s.date = %q{2011-02-20}
  s.default_executable = %q{dnsimple}
  s.description = %q{A ruby wrapper for the DNSimple API that also includes a command-line client.}
  s.email = %q{anthony.eden@dnsimple.com}
  s.executables = ["dnsimple"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README",
    "README.rdoc",
    "README.textile"
  ]
  s.files = [
    ".bundle/config",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README",
    "README.rdoc",
    "README.textile",
    "Rakefile",
    "VERSION",
    "bin/dnsimple",
    "bin/dnsimple.rb",
    "lib/dnsimple.rb",
    "lib/dnsimple/cli.rb",
    "lib/dnsimple/client.rb",
    "lib/dnsimple/commands/add_service.rb",
    "lib/dnsimple/commands/add_template_record.rb",
    "lib/dnsimple/commands/apply_template.rb",
    "lib/dnsimple/commands/check_domain.rb",
    "lib/dnsimple/commands/clear_domain.rb",
    "lib/dnsimple/commands/create_contact.rb",
    "lib/dnsimple/commands/create_domain.rb",
    "lib/dnsimple/commands/create_record.rb",
    "lib/dnsimple/commands/create_template.rb",
    "lib/dnsimple/commands/delete_contact.rb",
    "lib/dnsimple/commands/delete_domain.rb",
    "lib/dnsimple/commands/delete_record.rb",
    "lib/dnsimple/commands/delete_template.rb",
    "lib/dnsimple/commands/delete_template_record.rb",
    "lib/dnsimple/commands/describe_contact.rb",
    "lib/dnsimple/commands/describe_domain.rb",
    "lib/dnsimple/commands/describe_record.rb",
    "lib/dnsimple/commands/describe_service.rb",
    "lib/dnsimple/commands/describe_user.rb",
    "lib/dnsimple/commands/list_applied_services.rb",
    "lib/dnsimple/commands/list_available_services.rb",
    "lib/dnsimple/commands/list_contacts.rb",
    "lib/dnsimple/commands/list_domains.rb",
    "lib/dnsimple/commands/list_extended_attributes.rb",
    "lib/dnsimple/commands/list_records.rb",
    "lib/dnsimple/commands/list_services.rb",
    "lib/dnsimple/commands/list_template_records.rb",
    "lib/dnsimple/commands/list_templates.rb",
    "lib/dnsimple/commands/register_domain.rb",
    "lib/dnsimple/commands/remove_service.rb",
    "lib/dnsimple/commands/transfer_domain.rb",
    "lib/dnsimple/commands/update_contact.rb",
    "lib/dnsimple/commands/update_record.rb",
    "lib/dnsimple/contact.rb",
    "lib/dnsimple/domain.rb",
    "lib/dnsimple/error.rb",
    "lib/dnsimple/extended_attribute.rb",
    "lib/dnsimple/record.rb",
    "lib/dnsimple/service.rb",
    "lib/dnsimple/template.rb",
    "lib/dnsimple/template_record.rb",
    "lib/dnsimple/transfer_order.rb",
    "lib/dnsimple/user.rb",
    "spec/README",
    "spec/contact_spec.rb",
    "spec/domain_spec.rb",
    "spec/record_spec.rb",
    "spec/spec_helper.rb",
    "spec/template_spec.rb",
    "spec/user_spec.rb"
  ]
  s.homepage = %q{http://github.com/aetrion/dnsimple-ruby}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A ruby wrapper for the DNSimple API}
  s.test_files = [
    "spec/contact_spec.rb",
    "spec/domain_spec.rb",
    "spec/record_spec.rb",
    "spec/spec_helper.rb",
    "spec/template_spec.rb",
    "spec/user_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_dependency(%q<ruby-debug>, [">= 0"])
      s.add_dependency(%q<httparty>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
    s.add_dependency(%q<ruby-debug>, [">= 0"])
    s.add_dependency(%q<httparty>, [">= 0"])
  end
end

