HTTP/1.1 400 Bad Request
Server: nginx
Date: Mon, 27 Jul 2020 13:41:23 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
X-RateLimit-Limit: 2400
X-RateLimit-Remaining: 2398
X-RateLimit-Reset: 1595860823
Cache-Control: no-cache
X-Request-Id: 6986cca3-4f57-4814-9e81-1c484d61c7ea
X-Runtime: 0.007339
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none

{"message":"TLD .LOVE is not supported"}
