HTTP/1.1 200 OK
server: nginx
date: Sun, 28 Feb 2016 13:19:18 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
status: 200 OK
x-ratelimit-limit: 4000
x-ratelimit-remaining: 3996
x-ratelimit-reset: 1456669058
etag: W/"e0234245cb00aa260ccfa99a9a0b235e"
cache-control: max-age=0, private, must-revalidate
x-request-id: 414e9bf2-4681-4769-a3e0-ed9b8905edcc
x-runtime: 0.459391
strict-transport-security: max-age=31536000

{"data":[]}