HTTP/1.1 204 No Content
server: nginx
date: Tue, 19 Jan 2016 21:49:42 GMT
connection: keep-alive
status: 204 No Content
x-ratelimit-limit: 4000
x-ratelimit-remaining: 3999
x-ratelimit-reset: 1453243782
cache-control: no-cache
x-request-id: 10c8528b-569b-4152-a89c-fc9c5f94afe9
x-runtime: 0.029858
strict-transport-security: max-age=31536000

