HTTP/1.1 200 OK
server: nginx
date: Mon, 15 Feb 2016 17:06:09 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
status: 200 OK
x-ratelimit-limit: 4000
x-ratelimit-remaining: 3992
x-ratelimit-reset: 1455559348
etag: W/"cbb707ff6fc185d71f5a8df3110f1379"
cache-control: max-age=0, private, must-revalidate
x-request-id: 0109ea48-b7f0-4f78-a970-6866653b83eb
x-runtime: 0.087618
strict-transport-security: max-age=31536000

{"data":{"id":1,"url":"https://webhook.test","suppressed_at":null}}
