HTTP/1.1 204 No Content
server: nginx
date: Fri, 12 Feb 2016 11:15:46 GMT
connection: keep-alive
status: 204 No Content
x-ratelimit-limit: 4000
x-ratelimit-remaining: 3996
x-ratelimit-reset: 1455279163
cache-control: no-cache
x-request-id: 6a8e83f1-f80c-4dc0-a462-d63c932a59bb
x-runtime: 0.509466
strict-transport-security: max-age=31536000

