HTTP/1.1 200 OK
server: nginx
date: Mon, 25 Jan 2021 13:56:24 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
x-ratelimit-limit: 4800
x-ratelimit-remaining: 4766
x-ratelimit-reset: 1611583416
etag: W/"80ad3ad1e115a8123193447fa003f68a"
cache-control: max-age=0, private, must-revalidate
x-request-id: 8f3a9517-f623-4d14-be2b-3f332a4d7873
x-runtime: 0.010653
x-frame-options: DENY
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-download-options: noopen
x-permitted-cross-domain-policies: none
content-security-policy: frame-ancestors 'none'
strict-transport-security: max-age=31536000

{"data":{"id":41872,"domain_id":235146,"alias_email":"example@dnsimple.xyz","destination_email":"example@example.com","created_at":"2021-01-25T13:54:40Z","updated_at":"2021-01-25T13:54:40Z","active":true}}
