HTTP/1.1 204 No Content
server: nginx
date: Thu, 07 Jan 2016 18:06:28 GMT
connection: keep-alive
status: 204 No Content
x-ratelimit-limit: 4000
x-ratelimit-remaining: 3987
x-ratelimit-reset: 1452189987
cache-control: no-cache
x-request-id: 776cea0f-98ae-4550-9a2e-81f8ab27f82b
x-runtime: 0.099235
strict-transport-security: max-age=31536000

