HTTP/1.1 200 OK
Server: nginx
Date: Mon, 27 Jul 2020 13:58:50 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
X-RateLimit-Limit: 4800
X-RateLimit-Remaining: 4769
X-RateLimit-Reset: 1595859923
ETag: W/"54b4776b898065f2f551fc33465d0936"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 75c5090e-8000-4e95-a516-ffd09383f641
X-Runtime: 2.380524
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Strict-Transport-Security: max-age=31536000

{"data":{"premium_price":"2640.00","action":"registration"}}
