HTTP/1.1 500 Internal Server Error
Server: nginx
Date: Thu, 07 Jan 2016 16:35:37 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Status: 500 Internal Server Error
Cache-Control: no-cache
X-Request-Id: 0de115b1-2143-44e5-b117-c7f9c51ea2ff
X-Runtime: 0.022304

{"message":"Internal Server Error"}