HTTP/1.1 200 OK
server: nginx
date: Fri, 23 Sep 2016 09:06:13 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2396
x-ratelimit-reset: 1474622397
etag: W/"8e3d87c11204e76362765aea4c0916e0"
cache-control: max-age=0, private, must-revalidate
x-request-id: 426d0884-2583-45d8-8ab6-0e36050ba6dc
x-runtime: 0.011580
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: DENY
x-permitted-cross-domain-policies: none
x-xss-protection: 1; mode=block
strict-transport-security: max-age=31536000

{"data":{"tld":"com","tld_type":1,"whois_privacy":true,"auto_renew_only":false,"idn":true,"minimum_registration":1,"registration_enabled":true,"renewal_enabled":true,"transfer_enabled":true,"dnssec_interface_type":"ds","name_server_min":"2","name_server_max":"13"}}
