HTTP/1.1 200 OK
server: nginx
date: Sat, 13 Feb 2016 14:36:49 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
status: 200 OK
x-ratelimit-limit: 4000
x-ratelimit-remaining: 3994
x-ratelimit-reset: 1455377135
etag: W/"1063ebb3e281ca6e1941874002696cd7"
cache-control: max-age=0, private, must-revalidate
x-request-id: 34453d13-76ba-4f64-ad94-2d536c61826c
x-runtime: 1.408974
strict-transport-security: max-age=31536000

{"data":{"id":1,"domain_id":2,"expires_on":"2017-02-13","enabled":true,"created_at":"2016-02-13T14:34:50Z","updated_at":"2016-02-13T14:36:48Z"}}
