HTTP/1.1 200 OK
server: nginx
date: Fri, 17 May 2024 09:07:28 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
x-ratelimit-limit: 4800
x-ratelimit-remaining: 4748
x-ratelimit-reset: 1715936948
x-work-with-us: Love automation? So do we! https://dnsimple.com/jobs
etag: W/"a5eed9a071f03e10fc67001ccc647a94"
cache-control: max-age=0, private, must-revalidate
x-request-id: e42df983-a8a5-4123-8c74-fb89ab934aba
x-runtime: 0.025456
strict-transport-security: max-age=63072000

{"data":[{"id":24809,"domain_id":235146,"alias_email":".*@a-domain.com","destination_email":"jane.smith@example.com","created_at":"2017-05-25T19:23:16Z","updated_at":"2017-05-25T19:23:16Z","active":true}],"pagination":{"current_page":1,"per_page":30,"total_entries":1,"total_pages":1}}
