HTTP/1.1 200 OK
server: nginx
date: Tue, 19 Jan 2016 21:28:13 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
status: 200 OK
x-ratelimit-limit: 4000
x-ratelimit-remaining: 3995
x-ratelimit-reset: 1453239045
etag: W/"4a798ad8f083076b23d3eed622eefc2d"
cache-control: max-age=0, private, must-revalidate
x-request-id: c0e1e24f-d22d-4832-a30e-2f4ffc40b029
x-runtime: 0.053262
strict-transport-security: max-age=31536000

{"data":{"id":1,"account_id":1010,"label":"Default","first_name":"First","last_name":"User","job_title":"CEO","organization_name":"Awesome Company","email":"first@example.com","phone":"+18001234567","fax":"+18011234567","address1":"Italian Street, 10","address2":"","city":"Roma","state_province":"RM","postal_code":"00100","country":"IT","created_at":"2016-01-19T20:50:26Z","updated_at":"2016-01-19T20:50:26Z"}}
