HTTP/1.1 400 Bad Request
server: nginx
date: Mon, 15 Feb 2016 15:06:35 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
status: 400 Bad Request
x-ratelimit-limit: 4000
x-ratelimit-remaining: 3998
x-ratelimit-reset: 1455552316
cache-control: no-cache
x-request-id: 0c1507d3-4c03-4ba3-b2bd-b0cabf021ed8
x-runtime: 0.256476

{"message":"example.com may not be renewed at this time","errors":{}}
