HTTP/1.1 201 Created
Server: nginx
Date: Mon, 15 Feb 2016 15:19:24 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Status: 201 Created
X-RateLimit-Limit: 4000
X-RateLimit-Remaining: 3996
X-RateLimit-Reset: 1455552316
ETag: W/"3ee240b342a641fbc69f9c35fa77b53f"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: f888665c-8fcc-4ff1-a954-8ce7d7e19af6
X-Runtime: 3.506408
Strict-Transport-Security: max-age=31536000

{"data":{"id":1,"account_id":1010,"registrant_id":2,"name":"example.com","unicode_name":"example.com","token":"domain-token","state":"registered","auto_renew":false,"private_whois":false,"expires_on":"2018-01-16","created_at":"2016-01-16T16:08:50.649Z","updated_at":"2016-02-15T15:19:24.689Z"}}
