HTTP/1.1 400 Bad Request
server: nginx
date: Fri, 05 Sep 2025 06:50:48 GMT
content-type: application/json; charset=utf-8
content-length: 107
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2390
x-ratelimit-reset: 1757058040
x-work-with-us: Love automation? So do we! https://dnsimple.com/jobs
cache-control: no-cache
x-request-id: 254988cd-401b-4a32-b5d8-c25502573c9a
x-runtime: 0.105704
strict-transport-security: max-age=63072000

{"message":"Validation failed","errors":{"deletes":[{"index":0,"message":"Record not found ID=67622509"}]}}
