HTTP/1.1 400 Bad Request
server: nginx
date: Fri, 05 Sep 2025 06:58:03 GMT
content-type: application/json; charset=utf-8
content-length: 120
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2385
x-ratelimit-reset: 1757058040
x-work-with-us: Love automation? So do we! https://dnsimple.com/jobs
cache-control: no-cache
x-request-id: 44ce10e5-04cc-4428-8473-55739ff6e37a
x-runtime: 0.109317
strict-transport-security: max-age=63072000

{"message":"Validation failed","errors":{"creates":[{"index":1,"message":"The SPF record type has been discontinued"}]}}
