HTTP/1.1 200 OK
server: nginx
date: Thu, 24 Mar 2016 11:17:01 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
status: 200 OK
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2392
x-ratelimit-reset: 1458821049
etag: W/"cb540984f806b12ac437cc1f76092f90"
cache-control: max-age=0, private, must-revalidate
x-request-id: 0ea7bdd2-63ca-4eef-9c41-4a83d2fe0067
x-runtime: 2.845860
strict-transport-security: max-age=31536000

{"data":["ns1.dnsimple.com","ns2.dnsimple.com","ns3.dnsimple.com","ns4.dnsimple.com"]}