HTTP/1.1 201 Created
Server: nginx
Date: Tue, 19 Jan 2016 20:50:26 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Status: 201 Created
X-RateLimit-Limit: 4000
X-RateLimit-Remaining: 3997
X-RateLimit-Reset: 1453239045
ETag: W/"165299b0ea3e5c1c80f1ae622146626f"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 9f577b9e-5bc4-4a8f-adfb-09dbb1992b0e
X-Runtime: 0.061482
Strict-Transport-Security: max-age=31536000

{"data":{"id":595,"account_id":24,"label":null,"first_name":"foo","last_name":"foo","job_title":null,"organization_name":null,"email_address":"foo@example.com","phone":"+393392551831","fax":null,"address1":"foo","address2":null,"city":"foo","state_province":"RM","postal_code":"00171","country":"00171","created_at":"2016-01-19T20:50:26.066Z","updated_at":"2016-01-19T20:50:26.066Z"}}