HTTP/1.1 504 Gateway Timeout
Server: nginx
Date: Mon, 18 Dec 2017 10:54:48 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
X-RateLimit-Limit: 2400
X-RateLimit-Remaining: 2397
X-RateLimit-Reset: 1513597686
ETag: W/"10fc650d019e6bffa876f08bce8f3380"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 74059b13-9262-4e2d-b8ff-a833376dce19
X-Runtime: 0.408180
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: DENY
X-Permitted-Cross-Domain-Policies: none
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000

{"message":"Could not query zone, connection timed out"}
