HTTP/1.1 200 OK
Server: nginx
Date: Mon, 18 Dec 2017 10:48:06 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
X-RateLimit-Limit: 2400
X-RateLimit-Remaining: 2399
X-RateLimit-Reset: 1513597686
ETag: W/"10fc650d019e6bffa876f08bce8f3380"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 34c69751-ffee-4856-ac28-ead4f3a66e18
X-Runtime: 0.438473
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: DENY
X-Permitted-Cross-Domain-Policies: none
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000

{"data":{"distributed":true}}
