HTTP/1.1 201 Created
Server: nginx
Date: Tue, 16 Dec 2014 12:55:13 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Status: 201 Created
Strict-Transport-Security: max-age=631138519
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization,Accepts,Content-Type,X-DNSimple-Token,X-DNSimple-Domain-Token,X-CSRF-Token,x-requested-with
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
Location: https://api.sandbox.dnsimple.com/domains/dnsimple-sandbox.com/email_forwards/1
ETag: "4a3d3e2701d5863b915865b06fb5ddfb"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 043cfaab-ba96-4902-92de-e38cb2538a45
X-Runtime: 4.962496
Strict-Transport-Security: max-age=315360000

{"email_forward":{"id":1,"domain_id":1111,"from":"sender@dnsimple-sandbox.com","to":"receiver@example.com","created_at":"2014-12-16T12:55:13.697Z","updated_at":"2014-12-16T12:55:13.697Z"}}
