HTTP/1.1 200 OK
server: nginx
date: Thu, 24 Mar 2016 11:04:55 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
status: 200 OK
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2398
x-ratelimit-reset: 1458821048
etag: W/"6a2c0c6789d853473765a5fc5662da2e"
cache-control: max-age=0, private, must-revalidate
x-request-id: 3a7993e7-8b1e-47ce-a7a8-cc86b02904de
x-runtime: 0.324954
strict-transport-security: max-age=31536000

{"data":{"id":1,"account_id":1010,"name":"Alpha","sid":"alpha","description":"An alpha template.","created_at":"2016-03-22T11:08:58Z","updated_at":"2016-03-22T11:08:58Z"}}