HTTP/1.1 200 OK
Date: Thu, 10 Dec 2015 20:14:05 GMT
Status: 200 OK
Connection: close
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization,Accepts,Content-Type,X-DNSimple-Token,X-DNSimple-Domain-Token,X-CSRF-Token,x-requested-with
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Content-Type: application/json; charset=utf-8
Cache-Control: no-store, must-revalidate, private, max-age=0
X-Request-Id: 360532fd-7df5-4b9d-82d9-707495232709
X-Runtime: 0.351830
Set-Cookie: __profilin=p%3Dt; path=/
Set-Cookie: __profilin=p%3Dt; path=/
Set-Cookie: __profilin=p%3Dt; path=/
X-MiniProfiler-Ids: ["57flfc4miao2xtm0qi6t","3ob7yssth2tgz18xdhmh","lcx8amyy6mysu1rsv7d5","2qsm2f2xvqh224oqcnq9","qmhq7a2rqv5mtlz7e8bb"]
Transfer-Encoding: chunked

{"status":"disabled"}