HTTP/1.1 204 No Content
Server: nginx
Date: Tue, 16 Dec 2014 12:58:36 GMT
Connection: close
Status: 204 No Content
Strict-Transport-Security: max-age=631138519
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization,Accepts,Content-Type,X-DNSimple-Token,X-DNSimple-Domain-Token,X-CSRF-Token,x-requested-with
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
Cache-Control: no-cache
X-Request-Id: edba9357-649d-4bc3-a5aa-236123e53667
X-Runtime: 0.503655
Strict-Transport-Security: max-age=315360000

