HTTP/1.1 405 Method Not Allowed
server: nginx
date: Fri, 15 Apr 2016 14:15:04 GMT
connection: keep-alive
status: 405 Method Not Allowed
allow: DELETE, GET, HEAD, PATCH, POST
cache-control: no-cache
x-request-id: 64c0a5e1-4cbb-4287-98a7-93085a77ac55
x-runtime: 0.050104

