HTTP/1.1 200 OK
server: nginx
date: Wed, 16 Dec 2015 13:36:11 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
x-ratelimit-limit: 4000
x-ratelimit-remaining: 3997
x-ratelimit-reset: 1450272970
etag: W/"2679531e6cce6cd326f255255d7a0005"
cache-control: max-age=0, private, must-revalidate
x-request-id: a87f1b44-150a-4ed0-b7da-9301fa1465b0
x-runtime: 0.093714
strict-transport-security: max-age=31536000

{"data":[{"id":1},{"id":2}],"pagination":{"current_page":1,"per_page":2,"total_entries":5,"total_pages":3}}