HTTP/1.1 403 Forbidden
date: Tue, 24 Oct 2023 09:49:29 GMT
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2398
x-ratelimit-reset: 1698143967
content-type: application/json; charset=utf-8
x-work-with-us: Love automation? So do we! https://dnsimple.com/jobs
cache-control: no-cache
x-request-id: 5554e2d3-2652-4ca7-8c5e-92b4c35f28d6
x-runtime: 0.035309

{"message":"Permission Denied. Required Scope: billing:*:read"}
