HTTP/1.1 400 Bad Request
server: nginx
date: Mon, 08 Mar 2021 14:35:58 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2396
x-ratelimit-reset: 1615217645
cache-control: no-cache
x-request-id: e414a674-63bb-4e54-b714-db5b516bb190
x-runtime: 0.009579
x-frame-options: DENY
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-download-options: noopen
x-permitted-cross-domain-policies: none
content-security-policy: frame-ancestors 'none'

{"message":"TLD .PINEAPPLE is not supported"}