HTTP/1.1 201 Created
Server: nginx
Date: Mon, 22 Dec 2014 14:17:34 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Status: 201 Created
Strict-Transport-Security: max-age=631138519
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization,Accepts,Content-Type,X-DNSimple-Token,X-DNSimple-Domain-Token,X-CSRF-Token,x-requested-with
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
Location: /domains/example-1417880719.com/whois_privacy
ETag: "aa7e32e8efb9b3229cdc99ed786eea38"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 1659a34d-b523-4600-b47c-f7c794707036
X-Runtime: 0.999329
Strict-Transport-Security: max-age=315360000

{"whois_privacy":{"id":30,"domain_id":1744,"enabled":true,"expires_on":"2015-12-22"}}