HTTP/1.1 204 No Content
server: nginx
date: Mon, 11 Jul 2016 09:55:23 GMT
connection: keep-alive
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2398
x-ratelimit-reset: 1468233619
cache-control: no-cache
x-request-id: 334a5c9c-8205-414c-bca2-db0469ed0b4a
x-runtime: 0.385941
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: DENY
x-permitted-cross-domain-policies: none
x-xss-protection: 1; mode=block
strict-transport-security: max-age=31536000

