HTTP/1.1 504 Gateway Timeout
server: nginx
date: Mon, 18 Dec 2017 10:54:48 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2397
x-ratelimit-reset: 1513597686
etag: W/"10fc650d019e6bffa876f08bce8f3380"
cache-control: max-age=0, private, must-revalidate
x-request-id: 74059b13-9262-4e2d-b8ff-a833376dce19
x-runtime: 0.408180
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: DENY
x-permitted-cross-domain-policies: none
x-xss-protection: 1; mode=block
strict-transport-security: max-age=31536000

{"message":"Could not query zone, connection timed out"}
