HTTP/1.1 204 No Content
server: nginx
date: Mon, 25 Jan 2021 13:56:43 GMT
connection: keep-alive
x-ratelimit-limit: 4800
x-ratelimit-remaining: 4765
x-ratelimit-reset: 1611583416
cache-control: no-cache
x-request-id: bfaceb73-4fd3-4490-8528-472ec1df3526
x-runtime: 0.506670
x-frame-options: DENY
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-download-options: noopen
x-permitted-cross-domain-policies: none
content-security-policy: frame-ancestors 'none'
strict-transport-security: max-age=31536000

