HTTP/1.1 200 OK
server: nginx
date: Wed, 23 Nov 2022 18:05:39 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
status: 200 OK
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2391
x-ratelimit-reset: 1458821048
etag: W/"cb540984f806b12ac437cc1f76092f90"
cache-control: max-age=0, private, must-revalidate
x-request-id: e53ac7b5-0d26-45bc-9226-09c2d34be293
x-runtime: 0.192986
strict-transport-security: max-age=31536000

{"data":[{"id":1927,"zone_id":"example.com","parent_id":null,"name":"","content":"ns1.example.com","ttl":3600,"priority":null,"type":"NS","regions":["global"],"system_record":true,"created_at":"2022-11-23T18:05:39Z","updated_at":"2022-11-23T18:05:39Z"},{"id":1928,"zone_id":"example.com","parent_id":null,"name":"","content":"ns2.example.com","ttl":3600,"priority":null,"type":"NS","regions":["global"],"system_record":true,"created_at":"2022-11-23T18:05:39Z","updated_at":"2022-11-23T18:05:39Z"},{"id":1929,"zone_id":"example.com","parent_id":null,"name":"","content":"ns1.foo.bar","ttl":3600,"priority":null,"type":"NS","regions":["global"],"system_record":true,"created_at":"2022-11-23T18:05:39Z","updated_at":"2022-11-23T18:05:39Z"},{"id":1930,"zone_id":"example.com","parent_id":null,"name":"","content":"ns2.foo.bar","ttl":3600,"priority":null,"type":"NS","regions":["global"],"system_record":true,"created_at":"2022-11-23T18:05:39Z","updated_at":"2022-11-23T18:05:39Z"}]}
