HTTP/1.1 400 Bad Request
date: Tue, 24 Oct 2023 08:13:01 GMT
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2392
x-ratelimit-reset: 1698136677
content-type: application/json; charset=utf-8
x-work-with-us: Love automation? So do we! https://dnsimple.com/jobs
cache-control: no-cache
x-request-id: bdfbf3a7-d9dc-4018-9732-61502be989a3
x-runtime: 0.455303

{"message":"Invalid date format must be ISO8601 (YYYY-MM-DD)"}
