HTTP/1.1 204 No Content
Server: nginx
Date: Mon, 22 Dec 2014 18:12:42 GMT
Connection: close
Status: 204 No Content
Strict-Transport-Security: max-age=631138519
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization,Accepts,Content-Type,X-DNSimple-Token,X-DNSimple-Domain-Token,X-CSRF-Token,x-requested-with
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
Cache-Control: no-cache
X-Request-Id: 9367be2f-4081-4137-bf91-e3223189c046
X-Runtime: 2.193079
Strict-Transport-Security: max-age=315360000

