HTTP/1.1 201 Created
server: nginx
date: Tue, 03 May 2016 07:51:33 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
status: 201 Created
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2398
x-ratelimit-reset: 1462265481
etag: W/"a8518ecf2fd31e6c22b0acccb5cef797"
cache-control: max-age=0, private, must-revalidate
x-request-id: b2d51e79-b3d2-4abe-9184-155fb5546617
x-runtime: 0.190813
strict-transport-security: max-age=31536000

{"data":{"id":300,"template_id":268,"name":"","content":"mx.example.com","ttl":600,"priority":10,"type":"MX","created_at":"2016-05-03T07:51:33Z","updated_at":"2016-05-03T07:51:33Z"}}
