HTTP/1.1 400 Bad Request
server: nginx
date: Fri, 03 Mar 2017 15:20:28 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2395
x-ratelimit-reset: 1488554574
cache-control: no-cache
x-request-id: bf652af9-54cd-42c7-8fd3-2f52e2baea4b
x-runtime: 0.350846
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: DENY
x-permitted-cross-domain-policies: none
x-xss-protection: 1; mode=block

{"message":"Validation failed","errors":{"algorithm":["can't be blank"],"digest":["can't be blank"],"digest_type":["can't be blank"],"keytag":["can't be blank"]}}
