HTTP/1.1 200 OK
server: nginx
date: Thu, 24 Mar 2016 11:13:41 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
status: 200 OK
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2393
x-ratelimit-reset: 1458821048
etag: W/"e0234245cb00aa260ccfa99a9a0b235e"
cache-control: max-age=0, private, must-revalidate
x-request-id: c88385f9-c8f7-435a-9060-0b1a27488b2b
x-runtime: 0.206440
strict-transport-security: max-age=31536000

{"data":[]}