HTTP/1.1 400 
server: nginx
date: Fri, 21 Dec 2018 16:21:31 GMT
content-type: application/json; charset=utf-8
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2398
x-ratelimit-reset: 1545411828
cache-control: no-cache
x-request-id: 762d810d-a42c-4b1b-9382-9f56e5a339ff
x-runtime: 0.141307
x-frame-options: DENY
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-download-options: noopen
x-permitted-cross-domain-policies: none

{"message":"The whois privacy for example.com has just been renewed, a new renewal cannot be started at this time","errors":{}}