HTTP/1.1 200 
server: nginx
date: Fri, 21 Dec 2018 14:10:06 GMT
content-type: application/json; charset=utf-8
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2397
x-ratelimit-reset: 1545404617
etag: W/"23030fb7c68d7b7da22a374b5f1b1743"
cache-control: max-age=0, private, must-revalidate
x-request-id: 0c31a341-8078-4851-b232-d0f3819910c8
x-runtime: 2.015707
x-frame-options: DENY
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-download-options: noopen
x-permitted-cross-domain-policies: none
strict-transport-security: max-age=31536000

{"data":{"id":9,"domain_id":35879,"whois_privacy_id":478,"state":"new","expires_on":"2018-12-27","enabled":true,"created_at":"2018-12-21T14:10:04Z","updated_at":"2018-12-21T14:10:04Z"}}