HTTP/1.1 400 Bad Request
Server: nginx
Date: Thu, 10 Jan 2019 12:13:21 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
X-RateLimit-Limit: 2400
X-RateLimit-Remaining: 2397
X-RateLimit-Reset: 1547125899
Cache-Control: no-cache
X-Request-Id: 16cc92bb-fe38-434b-b483-602d77ac77d3
X-Runtime: 0.122201
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none

{"message":"The whois privacy for example.com has just been renewed, a new renewal cannot be started at this time","errors":{}}