HTTP/1.1 400 
server: nginx
date: Mon, 07 Jan 2019 13:58:34 GMT
content-type: application/json; charset=utf-8
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2399
x-ratelimit-reset: 1546873114
cache-control: no-cache
x-request-id: 5a43c5f0-4900-4563-ae9d-bd4a996312fa
x-runtime: 0.066139
x-frame-options: DENY
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-download-options: noopen
x-permitted-cross-domain-policies: none

{"message":"WHOIS privacy not found for example.com","errors":{}}