HTTP/1.1 200 OK
Server: nginx
Date: Mon, 15 Dec 2014 20:27:04 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Status: 200 OK
Strict-Transport-Security: max-age=631138519
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization,Accepts,Content-Type,X-DNSimple-Token,X-DNSimple-Domain-Token,X-CSRF-Token,x-requested-with
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
ETag: "882c85c0756e35625681ceb5262b0fe6"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 9a8e4510-d956-4a94-8a76-dd86669afef4
X-Runtime: 0.395985
Strict-Transport-Security: max-age=315360000

{"domain":{"id":1,"user_id":21,"registrant_id":321,"name":"example.com","unicode_name":"example.com","token":"domain-token","state":"registered","language":null,"lockable":false,"auto_renew":false,"whois_protected":false,"record_count":5,"service_count":1,"expires_on":"2015-09-27","created_at":"2012-09-27T14:25:57.646Z","updated_at":"2014-12-15T20:27:04.552Z"}}
