HTTP/1.1 200 OK
server: nginx
date: Mon, 15 Feb 2016 17:06:21 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
status: 200 OK
x-ratelimit-limit: 4000
x-ratelimit-remaining: 3991
x-ratelimit-reset: 1455559348
etag: W/"01f1ea26e8e06d8d969bf06678bf7d12"
cache-control: max-age=0, private, must-revalidate
x-request-id: bc611cd0-d1a9-48d0-b450-c9c86f0d0dcf
x-runtime: 0.104174
strict-transport-security: max-age=31536000

{"data":[{"id":1,"url":"https://webhook.test","suppressed_at":null},{"id":2,"url":"https://another.test","suppressed_at":null}]}
