HTTP/2 400 
server: nginx
date: Mon, 16 Feb 2026 11:30:46 GMT
content-type: application/json; charset=utf-8
content-length: 176
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2394
x-ratelimit-reset: 1771244870
x-work-with-us: Love automation? So do we! https://dnsimple.com/jobs
cache-control: no-cache
x-request-id: 5e818c7b-2bd3-478b-9b0d-23dcfedb276d
x-runtime: 0.030532
strict-transport-security: max-age=63072000

{"data":{"request_id":"5e818c7b-2bd3-478b-9b0d-23dcfedb276d","domain":"not..a..domain..name","availability":"unknown","errors":["'not..a..domain..name': Invalid domain name"]}}