HTTP/1.1 200 OK
server: nginx
date: Fri, 05 Jun 2020 18:23:53 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2392
x-ratelimit-reset: 1591384034
etag: W/"80c5827934c13b1ca87a587d96e7d1e8"
cache-control: max-age=0, private, must-revalidate
x-request-id: 9f4959ee-06a9-488c-906e-27a570cafbbf
x-runtime: 0.078429
x-frame-options: DENY
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-download-options: noopen
x-permitted-cross-domain-policies: none
strict-transport-security: max-age=31536000

{"data":{"id":361,"domain_id":182245,"registrant_id":2715,"state":"cancelled","auto_renew":false,"whois_privacy":false,"status_description":"Canceled by customer","created_at":"2020-06-05T18:08:00Z","updated_at":"2020-06-05T18:10:01Z"}}
