HTTP/1.1 204 No Content
server: nginx
date: Fri, 03 Mar 2017 15:25:00 GMT
connection: keep-alive
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2398
x-ratelimit-reset: 1488558240
cache-control: no-cache
x-request-id: 50271e09-f056-4413-9eea-87e097d43e8b
x-runtime: 0.306806
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: DENY
x-permitted-cross-domain-policies: none
x-xss-protection: 1; mode=block
strict-transport-security: max-age=31536000

