HTTP/1.1 201 Created
server: nginx
date: Fri, 09 Dec 2016 19:43:43 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2395
x-ratelimit-reset: 1481315246
etag: W/"e58e7ac3ad9e30162c5098f29f208066"
cache-control: max-age=0, private, must-revalidate
x-request-id: 0d00c622-9fc8-406a-93cb-d2c5d6ecd6b4
x-runtime: 6.483160
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: DENY
x-permitted-cross-domain-policies: none
x-xss-protection: 1; mode=block
strict-transport-security: max-age=31536000

{"data":{"id":1,"domain_id":999,"registrant_id":2,"state":"transferring","auto_renew":false,"whois_privacy":false,"created_at":"2016-12-09T19:43:41Z","updated_at":"2016-12-09T19:43:43Z"}}
