HTTP/1.1 200 OK
Server: nginx
Date: Mon, 15 Dec 2014 14:02:38 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Status: 200 OK
Strict-Transport-Security: max-age=631138519
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization,Accepts,Content-Type,X-DNSimple-Token,X-DNSimple-Domain-Token,X-CSRF-Token,x-requested-with
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
ETag: "44c42183525b49d84e8075628d6650b3"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: e687b0bc-5bdf-45bd-9db5-0108c87ecfac
X-Runtime: 0.075776
Strict-Transport-Security: max-age=315360000

{"dns_template":{"id":2651,"user_id":1120,"name":"Localhost","short_name":"localhost","description":"This is a test.","created_at":"2014-09-30T12:41:17.169Z","updated_at":"2014-09-30T12:44:20.101Z"}}
