HTTP/1.1 404 Not Found
Server: nginx/1.4.4
Date: Tue, 14 Jan 2014 18:28:07 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Status: 404 Not Found
X-Dnsimple-API-Version: 1.0.0
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization,Accepts,Content-Type,X-Dnsimple-Token,X-Dnsimple-Domain-Token,X-CSRF-Token,x-requested-with
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
X-UA-Compatible: IE=Edge,chrome=1
Cache-Control: no-cache
X-Request-Id: b7af596690cb83c7a7167f4d47aa50c3
X-Runtime: 0.044234

{"message":"Couldn't find Record with id=14395 [WHERE \"records\".\"domain_id\" = 6]"}