HTTP/1.1 204 No Content
server: nginx
date: Tue, 12 Jul 2016 08:56:00 GMT
connection: keep-alive
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2398
x-ratelimit-reset: 1468314483
cache-control: no-cache
x-request-id: 99c3fef2-d875-40fd-961c-194bffd694f1
x-runtime: 5.983300
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: DENY
x-permitted-cross-domain-policies: none
x-xss-protection: 1; mode=block
strict-transport-security: max-age=31536000

