HTTP/1.1 200 OK
Server: nginx
Date: Mon, 22 Dec 2014 15:45:22 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Status: 200 OK
Strict-Transport-Security: max-age=631138519
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization,Accepts,Content-Type,X-DNSimple-Token,X-DNSimple-Domain-Token,X-CSRF-Token,x-requested-with
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
ETag: "7dbe556effb089cdf9585c79812b75d5"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: a3bd2361-6b4d-4f78-b250-08401c62092e
X-Runtime: 0.038244
Strict-Transport-Security: max-age=315360000

[{"membership":{"id":155,"domain_id":1744,"user_id":19,"created_at":"2014-12-22T15:41:06.505Z","updated_at":"2014-12-22T15:41:06.505Z"}},{"membership":{"id":156,"domain_id":1744,"user_id":2,"created_at":"2014-12-22T15:44:30.833Z","updated_at":"2014-12-22T15:44:30.833Z"}}]