HTTP/1.1 204 No Content
server: nginx
date: Fri, 12 Feb 2016 11:13:38 GMT
connection: keep-alive
status: 204 No Content
x-ratelimit-limit: 4000
x-ratelimit-remaining: 3997
x-ratelimit-reset: 1455279163
cache-control: no-cache
x-request-id: 46e77cb2-157e-4740-8cd3-f20d4d653c95
x-runtime: 7.702967
strict-transport-security: max-age=31536000

