HTTP/1.1 200 OK
Server: nginx
Date: Mon, 15 Dec 2014 17:04:41 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Status: 200 OK
Strict-Transport-Security: max-age=631138519
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization,Accepts,Content-Type,X-DNSimple-Token,X-DNSimple-Domain-Token,X-CSRF-Token,x-requested-with
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
ETag: "535b1edb37f32b4388c1be8682e8c15a"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: ee1f0ee3-082a-4e59-8891-17d5068e857c
X-Runtime: 0.073436
Strict-Transport-Security: max-age=315360000

{"user":{"id":1,"email":"example@example.com","referral_token":"referral-token","api_token":"api-token","domain_count":32,"domain_limit":1000,"login_count":2,"failed_login_count":1,"created_at":"2011-03-17T21:30:25.731Z","updated_at":"2014-12-13T13:52:08.343Z"}}
