HTTP/1.1 204 No Content
server: nginx
date: Thu, 11 Aug 2016 10:23:46 GMT
connection: keep-alive
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2392
x-ratelimit-reset: 1470913058
cache-control: no-cache
x-request-id: 5867ab50-6237-4cf8-b220-51f5ef57debd
x-runtime: 0.582482
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: DENY
x-permitted-cross-domain-policies: none
x-xss-protection: 1; mode=block
strict-transport-security: max-age=31536000

