HTTP/1.1 200 OK
Server: nginx
Date: Mon, 30 Oct 2017 09:09:41 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
X-RateLimit-Limit: 2400
X-RateLimit-Remaining: 2399
X-RateLimit-Reset: 1509358181
ETag: W/"10fc650d019e6bffa876f08bce8f3380"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 91f124fc-671d-40fa-877b-0b222692f623
X-Runtime: 0.471005
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: DENY
X-Permitted-Cross-Domain-Policies: none
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000

{"data":{"distributed":true}}
