HTTP/1.1 200 OK
server: nginx
date: Mon, 30 Oct 2017 09:09:41 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2399
x-ratelimit-reset: 1509358181
etag: W/"10fc650d019e6bffa876f08bce8f3380"
cache-control: max-age=0, private, must-revalidate
x-request-id: 91f124fc-671d-40fa-877b-0b222692f623
x-runtime: 0.471005
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: DENY
x-permitted-cross-domain-policies: none
x-xss-protection: 1; mode=block
strict-transport-security: max-age=31536000

{"data":{"distributed":true}}
