HTTP/1.1 200 OK
server: nginx
date: Wed, 05 Oct 2016 09:59:48 GMT
content-type: application/json; charset=utf-8
connection: keep-alive
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2393
x-ratelimit-reset: 1475662530
etag: W/"92c807156882e555af8f7a5b93350e44"
cache-control: max-age=0, private, must-revalidate
x-request-id: 3b630702-46a9-4449-a320-b7ac903d2127
x-runtime: 0.405810
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: DENY
x-permitted-cross-domain-policies: none
x-xss-protection: 1; mode=block
strict-transport-security: max-age=31536000

{"data":{"id":5,"zone_id":"example.com","parent_id":null,"name":"","content":"mxb.example.com","ttl":3600,"priority":20,"type":"MX","regions":["global"],"system_record":false,"created_at":"2016-10-05T09:51:35Z","updated_at":"2016-10-05T09:51:35Z"}}
