HTTP/1.1 204 No Content
server: nginx
date: Sun, 21 Feb 2016 13:40:35 GMT
connection: keep-alive
status: 204 No Content
x-ratelimit-limit: 4000
x-ratelimit-remaining: 3990
x-ratelimit-reset: 1456063540
cache-control: no-cache
x-request-id: 9af6ab78-7ea8-4675-89f0-14d124fc7ca2
x-runtime: 3.038699
strict-transport-security: max-age=31536000

