HTTP/1.1 412 Precondition Failed
Server: nginx
Date: Wed, 18 Oct 2017 16:19:31 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Ratelimit-Limit: 2400
X-Ratelimit-Remaining: 2395
X-Ratelimit-Reset: 1508344422
ETag: W/"88b289ef19331082113a0c9cb32376da"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 10ecd819-fa64-4d32-839a-62185616ba23
X-Runtime: 0.168416
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: DENY
X-Permitted-Cross-Domain-Policies: none
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000

{"message":"Let's Encrypt feature is not enabled for the account test-account"}
