HTTP/1.1 204 No Content
server: nginx
date: Sat, 09 Jul 2016 11:12:42 GMT
connection: keep-alive
x-ratelimit-limit: 2400
x-ratelimit-remaining: 2398
x-ratelimit-reset: 1468066326
cache-control: no-cache
x-request-id: 30a3a44b-5792-4114-a355-a866603311ce
x-runtime: 0.087254
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: DENY
x-permitted-cross-domain-policies: none
x-xss-protection: 1; mode=block
strict-transport-security: max-age=31536000

