HTTP/1.1 201 Created
Server: nginx
Date: Mon, 22 Dec 2014 18:11:05 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Status: 201 Created
Strict-Transport-Security: max-age=631138519
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization,Accepts,Content-Type,X-DNSimple-Token,X-DNSimple-Domain-Token,X-CSRF-Token,x-requested-with
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
ETag: "0ebdecabeb62d0e8012597d52ad14e43"
Cache-Control: max-age=0, private, must-revalidate
X-Request-Id: 21d3a8e9-a6e6-4bc9-9f5a-92dfd6680f45
X-Runtime: 2.111712
Strict-Transport-Security: max-age=315360000

{"name":"ns1.example-1417880719.com","ip":"198.241.10.53"}