name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  wait-for-ci:
    name: Wait for CI
    runs-on: ubuntu-latest
    steps:
      - name: Wait for CI to pass
        uses: lewagon/wait-on-check-action@v1.5.0
        with:
          ref: ${{ github.sha }}
          running-workflow-name: Wait for CI
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  publish:
    name: Release to RubyGems
    needs: wait-for-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Release Gem
        uses: simplyqio/publish-rubygems-action@2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          RELEASE_COMMAND: "rake build && gem push pkg/*.gem"
